apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: common

.common: &common
  upgradeOnChange: true

.common-values: &common-values
  replicas: "1"
  logLevel: "DEBUG"
  lifecycle.preStop.exec.command:
    - "sleep"
    - '"10"'
  image.repository: "nexuszolara.me"
  imagePullSecrets:
  - name: regcred-harbor

.common-api-values: &common-api-values
  <<: *common-values
  ingress:
    hosts[0]: "{{.SK_HOST}}"
    extraAnnotations:
      nginx\.ingress\.kubernetes\.io/configuration-snippet: |
        #proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
        more_set_headers "Access-Control-Expose-Headers: www-authenticate";

.common-vault-values: &common-vault-values
  <<: *common-values
  database:
    host: "postgres.database.svc.cluster.local"

deploy:
  helm:
    releases:
      ##############################################
      #             ingress-controller             #
      ##############################################
      - name: "{{.SK_ENV_NAME}}-ingress-nginx"
        remoteChart: ingress-nginx/ingress-nginx
        namespace: ingress-nginx
        version: "{{.INGRESS_CONTROLLER_VERSION}}"
        valuesFiles:
        - "{{ .SK_VALUES_PATH }}/ingress-nginx.yaml"
        <<: *common

      ############################################
      #           pki-vault-service           #
      ############################################
      - name: "{{.SK_ENV_NAME}}-pki-vault-service"
        remoteChart: oci://nexuszolara.me/zolara-microservice/pki-vault-service-helm
        namespace: vault
        version: "{{.PKI_VAULT_SERVICE_VERSION}}"
        setValueTemplates:
          <<: *common-vault-values
        <<: *common

      ############################################
      #                 user-api                 #
      ############################################
      - name: "{{.SK_ENV_NAME}}-user-api"
        remoteChart: oci://nexuszolara.me/zolara-microservice/user-api-helm
        namespace: api
        version: "{{.USER_API_VERSION}}"
        setValueTemplates:
          <<: *common-api-values
        <<: *common
        
      ############################################
      #                  redis                   #
      ############################################
      - name: "{{.SK_ENV_NAME}}-redis"
        remoteChart: bitnami/redis
        namespace: redis
        version: "{{.REDIS_HELM_VERSION}}"
        valuesFiles:
          - "{{ .SK_VALUES_PATH }}/redis.yaml"
        <<: *common
