- name: Build db image running ./runDB.sh script in db directory
  ansible.builtin.shell:
    cmd: ./runDB.sh
  args:
    chdir: "{{ work_dir }}/db"
  become_user: root

- name: Build front image
  community.docker.docker_image_build:
    name: front:ZOLARA_TAG
    path: "{{ work_dir }}/front"
    dockerfile: Dockerfile
  become_user: root

- name: Run docker compose in the back directory
  community.docker.docker_compose_v2:
    project_src: "{{ work_dir }}/back"
    state: present
    build: always
  become_user: root