- name: Unlock the db repository
  ansible.builtin.shell:
    cmd: git-crypt unlock
  args:
    chdir: "{{ work_dir }}/db"

- name: Unlock the back repository
  ansible.builtin.shell:
    cmd: git-crypt unlock
  args:
    chdir: "{{ work_dir }}/back"